# User config
author: "j0r15"
#tagline: "Pineapple Certfied Jekyll Theme"
#description: "In 1493, explorer Christopher Columbus found pineapples on Guadeloupe Island in the Caribbean. Pineapple on pizza soon followed..."
#keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "contact@jrsvs.nl"
#linkedin: "https://www.linkedin.com/"
#twitter: "https://twitter.com/"
github: "https://github.com/j0r15"
instagram: "https://instagram.com/j0r1_5"

# Site config
baseurl: "/"
highlighter: "rouge"
sass:
  sass_dir: assets/scss
  style: compressed
